### ISSUE TITLE
Duplicate metrics from `resilience4j.circuitbreaker.calls`

### ISSUE THREAD

**Issue by OathMeadow** [spring-cloud/spring-cloud-circuitbreaker#213] opened 2024-09-05 11:50 UTC
We moved over from the old `Hystrix` to `Resilience4j`. We decided to go with `Spring Cloud Circuit Breaker` as it fit our needs.
After deployment we realized quickly the metrics looked strange, as the picture shows, when comparing the old metrics from `Hystrix` with the new from Resilience4j. They seemed to somehow have doubled.
![image](https://github.com/user-attachments/assets/43001e45-343c-4500-b6cc-8eab12020072)

I could reproduce this with a simple JUnit tests that runs a circuit breaker for 200 times. When I check the Meter registry, I could see that the metric `resilience4j.circuitbreaker.calls` had counted 400 times. So it is obviously a double. Then I spend probably 4 hours debugging through `Spring Cloud Circuit Breaker` and `resilience4j-spring-boot3` classes and autoconfiguration, but could not find the root cause, but I found a solution.

If we configure the following: `resilience4j.circuitbreaker.metrics.legacy.enabled=true` and re-run the tests, we did not get any duplicate metrics any more as the test showed 200 counts. So the issue has something to do with this parameter.
This parameter is set to false by default.

So the dilemma here is I do not know if I should have reported the issue here or at `resilience4j`. I humbly apologize if this is the wrong repo. However, I suspect that the combination of `Spring Cloud Circuit Breaker` and `resilience4j-spring-boot3` might cause this issue. This is just a theory, I have not yet confirmed it.

With `resilience4j.circuitbreaker.metrics.legacy.enabled=false` (default)
![image](https://github.com/user-attachments/assets/8c6a5c1e-d446-4ee1-a6cd-eb1ee4ff3f8b)

With `resilience4j.circuitbreaker.metrics.legacy.enabled=true`
![image](https://github.com/user-attachments/assets/6d3c1c81-e0ea-41af-8308-a0213a04afc3)

We use:
`Spring Boot 3.3.2`
`Spring Cloud 2023.0.3`

**Comment by OathMeadow** [comment] 2024-09-05 16:07
@ryanjbaxter 
I made a quick test it as you said by only using Resilience4j Spring Boot 3, without any custom configurations.

As we can see below it works as expected: 
![image](https://github.com/user-attachments/assets/a98997e6-5374-4be2-a6d7-ab064fcc12d3)

```
import io.github.resilience4j.circuitbreaker.annotation.CircuitBreaker;
import org.springframework.stereotype.Component;

@Component
public class CB {

    @CircuitBreaker(name = "MYCB", fallbackMethod = "fallback")
    public String test() {
        return "OK";
    }

}
```

So it seems to be a conflict with autoconfiguration of `Spring Boot Circuit Breaker` and `Resilience4j Spring Boot`.
It seems to have something to do with multiple consumers for the `EventProcessor` being added that will produce metrics twice for the same event. I believe the same consumer is added by `Resilience4j Spring Boot` and another by `Spring Boot Circuit Breaker`.

My colleague has been checking deeper and I believe he will write a more detailed result.

**Comment by cbarreholm** [comment] 2024-09-05 19:23
I'm a team mate of the reporter. I ran the same unit test that he did.

I noticed that the timer is invoked twice, because the same EventProcess instance get call twice.

By setting a breakpoint in EventProcessor line 40 with condition 
`this instanceof CircuitBreakerStateMachine.CircuitBreakerEventProcessor && className.equals("io.github.resilience4j.circuitbreaker.event.CircuitBreakerOnSuccessEvent")`
I could see that the same processor instance is indeed registered twice. Why?

Here is the diff of the two call stacks:
![image](https://github.com/user-attachments/assets/98688a70-e566-4ae5-8eac-f5de99a2f482)
I interpret it as if the registration of the processor triggers an `onEntryAddedEvent` .

With
`resilience4j.circuitbreaker.metrics.legacy.enabled=false`
I can see that I have two consumers referencing the same time instance:
![image](https://github.com/user-attachments/assets/8a83ba8f-c039-4328-a95e-889066fd0925)
With
`resilience4j.circuitbreaker.metrics.legacy.enabled=true`
I can see that I have two consumers referencing the different timer instances:
![image](https://github.com/user-attachments/assets/85fb6d91-4717-42d3-b2de-714ae6293770)

I'm continuing the investigation and trying to nail it down in the debugger, but I have to call it then day now. I'll update any further findings I get.

**Comment by ryanjbaxter** [comment] 2024-09-05 20:21
Thanks appreciate the update. Please keep me updated on what you find.

**Comment by cbarreholm** [comment] 2024-09-09 21:07
We have made some progress. The reporter has better knowledge and can provide better feedback, but his out-of-office for a while. 

The short versions is that there is an issue with the robustness of the setup of Spring Autoconfiguration. You may end up in a situation where you get two `TaggedCircuitBreakerMetricsPublisher` beans. 

The first one is created by `io.github.resilience4j.springboot3.circuitbreaker.autoconfigure.CircuitBreakerMetricsAutoConfiguration.taggedCircuitBreakerMetricsPublisher`.

The second one is created by `org.springframework.cloud.circuitbreaker.resilience4jResilience4JAutoConfiguration.MicrometerResilience4JCustomizerConfiguration`  even if there is a condition `@ConditionalOnMissingBean({ TaggedCircuitBreakerMetricsPublisher.class })`. 

To quote the JavaDoc of ConditionalOnMissingBean

> If a candidate bean may be created by another auto-configuration, make sure that the one using this condition runs after.

There is no such guard here.

In our specific case we had code that caused the autoconfiguration to run in the "incorrect" order. We changed some of our code that in turn resulted in the two above autoconfigurations to run in the "correct" order. It "works" but it's not entirely robust.

I hope this explains it well enough.

**Comment by ryanjbaxter** [comment] 2024-09-24 20:04
Thanks @cbarreholm and @OathMeadow! 

Would it be possible to create a sample that recreates the issue?

Seems like you have to have `resilience4j.circuitbreaker.metrics.legacy.enabled=true` for the issue to occur and that seems to be the default behavior since `matchIfMissing` is set to `true` in the Resilience4J auto-configuration.  

I could imagine two solutions.  The first solution would be to add `@AutoConfigureAfter(CircuitBreakerMetricsAutoConfiguration.class)`.  The second solution would be to disable `MicrometerResilience4JCustomizerConfiguration` when `resilience4j.circuitbreaker.metrics.legacy.enabled=false` (or is missing).  The first solution would be preferable IMO.  A sample to test these solutions out would be very helpful.

**Comment by spring-cloud-issues** [comment] 2024-10-01 20:05
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by cbarreholm** [comment] 2024-10-02 20:44
@OathMeadow I believe thtat you are better suited for reviewing the suggested solution.
I tried to create a sample project to reproduce it, but failed. I guess that we could at least beta test a possible solution by checking out our project at the failing version and run a potential fix.

**Comment by ryanjbaxter** [comment] 2024-10-02 21:12
@cbarreholm @OathMeadow I created a PR with the proposed change
https://github.com/spring-cloud/spring-cloud-circuitbreaker/pull/218

If you want to use that to test it out in your environment that would be great!

**Comment by ryanjbaxter** [comment] 2024-10-16 14:28
I have merged the PR in hopes that it addresses the issue.  It is a low risk fix in either case.

**Closed by ryanjbaxter** 2024-10-16 14:28 UTC
Labels: feedback-provided
