### ISSUE TITLE
Issue with recordResult predicate config

### ISSUE THREAD

**Issue by Raghava2016** [spring-cloud/spring-cloud-circuitbreaker#154] opened 2022-08-22 17:53 UTC
springframework.cloud.circuitbreaker.resilience4j: 2.1.1

how do I achieve following thing?  

I would like to read following properties from YML file. 

resilience4j.circuitbreaker:
  instances:
    redis:
      failureRateThreshold: 50
       minimumNumberOfCalls: 10
       slidingWindowType: TIME_BASED
       slidingWindowSize: 10

Since it's not feasible to set recordResultPredicate in YML file, I would like to use builder to do so.

    @Bean
    public Customizer<ReactiveResilience4JCircuitBreakerFactory> defaultCustomizer() {
        return factory -> factory.configure(builder -> builder
            .circuitBreakerConfig(getCircuitBreakerConfig(CircuitBreakerConfig.ofDefaults())), "redis");
    }

    private CircuitBreakerConfig getCircuitBreakerConfig(CircuitBreakerConfig config) {
        return CircuitBreakerConfig.from(config)
            .recordResult(CustomRedisRateLimiter.recordResultPredicate())
            .build();
    }

I want to CircuitBreakerConfig to have all config from YML file along with recordResultPredicate value. 

I am unable to achieve it as I am not getting access to config from YML file. Please advice.

**Comment by ryanjbaxter** [comment] 2022-08-23 00:31
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-cloud-issues** [comment] 2022-08-30 00:32
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2022-09-06 00:32
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed** 2023-01-12 01:10 UTC
