### ISSUE TITLE
ReactiveResilience4j event consumer not working

### ISSUE THREAD

**Issue by p4w4n** [spring-cloud/spring-cloud-circuitbreaker#158] opened 2022-11-10 06:14 UTC
Hi,

I am using Spring Cloud Gateway and has created a below bean.

```
    @Bean
    @RefreshScope
    public Customizer<ReactiveResilience4JCircuitBreakerFactory> hgwCircuitBreaker(){
        return factory -> {
            routeCircuitBreakers.forEach((id,name) ->{

                factory.configure(builder -> builder.circuitBreakerConfig(CircuitBreakerConfig.ofDefaults()).build()
                                .setCircuitBreakerConfig(CircuitBreakerConfig.custom().minimumNumberOfCalls(10).failureRateThreshold(20).build())
                        , id);
                if(name.getSelectAttribute() != ""){
                    HashMap<String, CBFilterCfg> cbFilters = name.getCbFilters();
                    if(!cbFilters.isEmpty()) {
                        cbFilters.forEach((filterId, cbFilterCfg) -> {
                            factory.configure(builder -> builder.circuitBreakerConfig(CircuitBreakerConfig.ofDefaults()).build()
                                            .setCircuitBreakerConfig(CircuitBreakerConfig.custom().minimumNumberOfCalls(1).failureRateThreshold(1).build())
                                    , id + "-" + cbFilterCfg.getAttributeValue());

                        });
                    }
                }

            });

            Customizer.once(circuitBreaker -> {
                circuitBreaker.getEventPublisher()
                        .onEvent(event -> LOGGER.info(Logger.EVENT_SUCCESS, event.getCircuitBreakerName()+" : "+event));
            }, CircuitBreaker::getName);


            
        };
    }
````
But I am not seeing any log related to any event in Circuit Breaker. Do I need to create a consumer somewhere so that it can start logging the events?

Thanks!!!

**Comment by ryanjbaxter** [comment] 2022-11-14 00:58
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-cloud-issues** [comment] 2022-11-21 01:02
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2022-11-28 01:02
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed** 2023-01-12 01:10 UTC
Labels: waiting-for-triage
