### ISSUE TITLE
Problems with factory initialisation order in bean resolution

### ISSUE THREAD

**Issue by arcuri82** [spring-cloud/spring-cloud-circuitbreaker#78] opened 2020-08-07 22:15 UTC
Updating a code example from Hystrix to Spring Cloud Circuit Breaker using Resilience4J.
It did not work, at first.
After couple of hours of debugging, managed to find a (ugly) workaround. 
Not sure if this is a bug, or intended behaviour. But, in this latter case, the examples and documentation should be improved to avoid others like me having the same issue.

Code snippets in Kotlin. Full code example can be found [here](https://github.com/arcuri82/testing_security_development_enterprise_systems/tree/2020-autumn/advanced/rest/circuit-breaker)

Using Spring Cloud `Hoxton.RELEASE`.

Assume a custom default configuration, defined in a `@SpringBootApplication`

```
    @Bean
    fun globalCustomConfiguration(): Customizer<Resilience4JCircuitBreakerFactory> {
```

Now, injecting a factory in a Rest controller:

```
@RestController
class YRest(private val circuitBreakerFactory : Resilience4JCircuitBreakerFactory){ 

      private  var cb : CircuitBreaker? =null
```

to instantiate the CircuitBreaker `cb` only once, I thought I could do something like:

```
   @PostConstruct
    fun init(){
        cb = circuitBreakerFactory.create("circuitBreakerToX")
    }
```

Unfortunately, that does not work, as by the time it is called, `globalCustomConfiguration` has not even been instantiated.
Adding something like `@DependsOn("globalCustomConfiguration")` did not help either.

However, the workaround was, before calling `cb.run`, to instantiate it if null, ie.:

```
if (cb == null)
            cb = circuitBreakerFactory.create("circuitBreakerToX")

cb!!.run //...
```

**Comment by InternetPseudonym** [comment] 2020-09-16 09:48
spring beans are singletons by default - you dont need to check them manually

**Comment by arcuri82** [comment] 2020-09-16 12:53
@InternetPseudonym  thanks, but I am not sure I am following your comment here. I know that Spring Beans are singletons by default. The problem here is that Spring seems to inject a bean (`circuitBreakerFactory`) before it is fully initialized. 
So wondering if it is a bug in `Resilience4JCircuitBreakerFactory`, or rather it should be used in a different way

**Comment by ryanjbaxter** [comment] 2020-09-21 14:44
What if you create the CB in the constructor?

https://github.com/spring-cloud/spring-cloud-circuitbreaker/pull/56/files#diff-a5678afe8ab680155b2c7ebc5dbae83eR199

**Comment by arcuri82** [comment] 2020-09-21 18:59
@ryanjbaxter  thanks for the suggestion. Unfortunately, it does not work :(

**Comment by ryanjbaxter** [comment] 2021-01-06 15:55
@arcuri82 I am trying to reproduce this problem but am failing to reproduce it using Hoxton SNAPSHOTs and the link to your sample is not working.  Are you still having this problem?

**Comment by arcuri82** [comment] 2021-01-10 21:27
@ryanjbaxter sorry, that was in a branch that I deleted sometime ago, forgetting that it was referenced here... 

Anyway, I am still seeing this problem in SpringBoot 2.3.5 with Cloud `Hoxton.RELEASE`. 

You can look at the following [YRestTest.kt](https://github.com/arcuri82/testing_security_development_enterprise_systems/blob/master/advanced/rest/circuit-breaker/src/test/kotlin/org/tsdes/advanced/rest/circuitbreaker/YRestTest.kt) test, which is currently passing, as I am using a workaround.

However, if you edit the [YRest](https://github.com/arcuri82/testing_security_development_enterprise_systems/blob/master/advanced/rest/circuit-breaker/src/main/kotlin/org/tsdes/advanced/rest/circuitbreaker/YRest.kt) class, by initializing `cb` in the `PostConstruct` instead of the REST handler, then you will see the problem

**Comment by ryanjbaxter** [comment] 2021-01-12 01:16
Can you try Hoxton.SR9?

If that still doesn't work can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-cloud-issues** [comment] 2021-01-19 01:17
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by arcuri82** [comment] 2021-01-20 19:26
with `Hoxton.SR9`, it works fine ;)

**Comment by ryanjbaxter** [comment] 2021-01-20 20:55
Great I will close this then.  Thanks!

**Closed by ryanjbaxter** 2021-01-20 20:55 UTC
Labels: feedback-provided

**Comment by kihwankim** [comment] 2022-07-09 11:23
I had the same problem, but I found a solution through the code below.

```
@RestController
class EndPointController(
    private val circuitBreakerFactory: CircuitBreakerFactory<*, *>
) 
```

The reason for this problem is that there is no generic type. So, you need to add wildcard generic type to make DI possible
